apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tetris-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tetris-from-ingress-virtual-service
  labels:
    from: ingress-virtual-service
spec:
  hosts:
    - "*"
  gateways:
    - tetris-gateway
  http:
    - match:
        - uri:
            prefix: /tetris/
      rewrite:
        uri: /
      route:
        - destination:
            host: tetris-service
            port:
              number: 80
